import Foundation

public actor AnalysisStore {
    private(set) var expected: [TraceEvent] = []
    private(set) var actual: [TraceEvent] = []
    private(set) var firstDivergenceIndex: Int? = nil

    public init() {}

    public func setExpected(_ events: [TraceEvent]) {
        expected = events
    }

    public func setActual(_ events: [TraceEvent]) {
        actual = events
    }

    public func computeFirstDivergence() {
        let n = min(expected.count, actual.count)
        for i in 0..<n {
            if expected[i] != actual[i] {
                firstDivergenceIndex = i
                return
            }
        }
        if expected.count != actual.count {
            firstDivergenceIndex = n
        } else {
            firstDivergenceIndex = nil
        }
    }

    public func buildReport(expectedPath: String, actualPath: String) -> DivergenceReport {
        let idx = firstDivergenceIndex
        let expectedEvent = idx.flatMap { $0 < expected.count ? expected[$0] : nil }
        let actualEvent = idx.flatMap { $0 < actual.count ? actual[$0] : nil }

        return DivergenceReport(
            traceA: expectedPath,
            traceB: actualPath,
            firstDivergenceEvent: idx,
            expected: expectedEvent,
            actual: actualEvent,
            notes: "Generated by DetTraceAnalyzer using Swift concurrency."
        )
    }
}
